config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end

  root to: 'posts#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { maximum: 30}

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  
  has_many :posts
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_user_url, notice: "ユーザー「#{@user.name}」を削除しました"
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url unless current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = current_user.posts
  end

  def show
    @post = current_user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))
    if @post.save
      redirect_to @post, notice: "つぶやきました"
    else
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    post = current_user.post.find(params[:id])
    post.update!(post_params)
    redirect_to posts_url, notice: 'つぶやきを更新しました'
  end

  def destroy
    post = current_user.post.find(params[:id])
    post.destroy
    redirect_to posts_url, notice: 'つぶやきを削除しました'
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user
      session[:user_id] = user.id
      redirect_to root_url, notice: 'ログインしました'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li = message

= form_with model: [:admin, @user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = User.human_attribute_name(:name)
      th = User.human_attribute_name(:email)
      th = User.human_attribute_name(:admin)
      th = User.human_attribute_name(:created_at)
      th = User.human_attribute_name(:updated_at)
      th
    tbody
     - @users.each do |user|
      tr
        td = link_to user.name, [:admin, user]
        td = user.email
        td = user.admin? ? 'あり' : 'なし'
        td = user.created_at
        td = user.updated_at
        td
          = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary'
          = link_to '削除', [:admin, user], method: :delet, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danfer'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザーの詳細

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

  table.table.table-hover
    tbody
      tr
        th = User.human_attribute_name(:id)
        td = @user.id
      tr
        th = User.human_attribute_name(:name)
        td = @user.name
      tr
        th = User.human_attribute_name(:email)
        td = @user.email
      tr
        th = User.human_attribute_name(:admin)
        td = @user.admin? ? 'あり' : 'なし'
      tr
        th = User.human_attribute_name(:created_at)
        td = @user.created_at
      tr
        th = User.human_attribute_name(:updated_at)
        td = @user.updated_at

= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Twitter
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar-navbar-expand-md.navbar-light.bg-light
      .navbar-brand TwitterLike

      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item = link_to 'タスク一覧', posts_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item = link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
          li.nav-item = link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item = link_to 'ログイン', login_path, class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield

app/views/posts/_form.html.slim
- if post.errors.present?
  ul#error_explanation
    - post.errors.full_messages.each do |message|
      li = message

= form_with model: post, local: true do |f|
  .form-group
    = f.label :content
    = f.text_area :content, rows: 5, class: 'form-control', id: 'post_content', placeholder: '今何してる？'
  = f.submit 'つぶやく', class: 'btn btn-primary'

app/views/posts/_home.html.slim
.nav.justify-content-end
  = link_to '一覧', posts_path, class: 'nav-link'

app/views/posts/edit.html.slim
h1 つぶやき編集

=render partial: 'home'

= render partial: 'form', locals: { post: @post}

app/views/posts/index.html.slim
.card.bg-dark.text-white.text-center
  img src='assets/desktop.png' class='card-img' alt='topimag' height='400'
  .card-img-overlay style="top: 25%;"
    h1.card-title 気ままにつぶやこう
    p.card-text.m-md-3
      = link_to 'ログイン', new_post_path, class: 'btn btn-primary mr-3'
      = link_to 'サインイン', new_post_path, class: 'btn btn-success'

h1 全てのつぶやき
= link_to 'つぶやく', new_post_path, class: 'btn btn-primary'


- @posts.each do |post|
  .m-3
    .card
      .card-header 
        | ユーザーネームとアイコン
      .card-body
        h5.card-title 
          | #{post.content}
        = link_to '詳細', post_path(post), class: 'btn btn-primary mr-3'
        = link_to '編集', edit_post_path(post), class: 'btn btn-success mr-3'
        = link_to '削除', post, method: :delete, data: { confirm: 'つぶやきを削除します。よろしいですか？' }, class: 'btn btn-danger'
        

app/views/posts/new.html.slim
h1 つぶやき作成

=render partial: 'home'

= render partial: 'form', locals: { post: @post}

app/views/posts/show.html.slim
h1 つぶやき詳細

.nav.justify-content-end
  = link_to '一覧', posts_path, class: 'nav-link'

.m-3
  .card
    .card-header 
      | ユーザーネームとアイコン
    .card-body
      h5.card-title 
        | #{@post.content}
        p 
          small #{@post.created_at}